spring.datasource.url=jdbc:postgresql://neondb_owner:npg_i4PB8gVlZvdL@ep-cool-glade-apfa5zko-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
