spring.datasource.url=jdbc:postgresql://ep-cool-glade-apfa5zko-pooler.c-7.us-east-1.aws.neon.tech/garagedb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_LOAjg82uCHhU
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}
